#!/bin/sh
# File generated by ocamlbuild

cd /mnt/d/cours/GITENT/projetgrammaire

rm -f ast.cmi
rm -f ast.cmo
rm -f lexer.ml
rm -f parser.ml
rm -f token.cmi
rm -f token.cmo
# Also clean the script itself
rm -f /mnt/d/cours/GITENT/projetgrammaire/_build/sanitize.sh
